name: Test
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install plugin
      run: |
        pip install pytest-github-actions-annotate-failures
    - name: check flake8
      run: |
        command: ./script/flake8-check.sh
    - name: Test with pytest
      run: |
        ./script/test_github.sh
